[package]
name = "lab3_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
fs = "0.0.5"
image = "0.25.2"
io = "0.0.2"
minifb = "0.27.0"
miniquad = "0.4.5"
mouse_position = "0.1.4"
nalgebra-glm = "0.3"
once_cell = "1.10"
rodio = "0.19"



